# This first workflow is intentionally tiny.
# It helps students see what a GitHub Actions run looks like.
name: 01 Hello Workflow

on:

  pull_request:
      types: [closed]
      branches: [main]
      paths:
       - ".github/workflows/01-hello.yml"
  
  workflow_dispatch:

jobs:

  specific_review_requested:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo 'A new pull request is opened'

